version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - node-network
    env_file:
      - .env
  
  redis:
    image: redis:latest
    container_name: redis-boilerplate-dev
    restart: always
    networks:
      - node-network
    ports:
      - '6379:6379'
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-boilerplate-dev
    restart: always
    ports:
      - '5672:5672'   # AMQP protocol port
      - '15672:15672'
    networks:
      - node-network # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    env_file:
      - .env

volumes:
  dbdata:
    driver: local

networks:
  node-network:
    driver: bridge
